import { type NextPage } from "next";
import Head from "next/head";
import clx from "classnames";

import { ItemForm, PeopleInput, ThemeSwitch } from "@components/index";
import { FormProvider } from "@contexts/Form";
import { PeopleProvider } from "@contexts/PeopleContext";
import { useTheme } from "@contexts/ThemeContext";

const Home: NextPage = () => {
  const { theme } = useTheme();

  return (
    <div className={clx({ dark: theme === "dark" })}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-white dark:bg-black">
        <div className="container flex max-w-2xl flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex w-full items-center justify-between">
            <h1 className="m-0 text-5xl font-extrabold tracking-tight text-black dark:text-white sm:text-[5rem]">
              Fair
              <span className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-transparent">
                Share
              </span>
            </h1>
            <ThemeSwitch />
          </div>
          <PeopleProvider>
            <FormProvider>
              <PeopleInput />
              <ItemForm />
            </FormProvider>
          </PeopleProvider>
        </div>
      </main>
    </div>
  );
};

export default Home;
